package com.example.android.unscramble.ui.game

const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

val allWordsList: List<String> =
    listOf("binatang",
        "otomatis",
        "anekdot",
        "huruf",
        "semua",
        "mengagumkan",
        "bangkit",
        "balon",
        "basket",
        "bangku",
        "terbaik",
        "ulang tahun",
        "buku",
        "tas",
        "kamera",
        "berkemah",
        "lilin",
        "kucing",
        "kol",
        "mengobrol",
        "anak",
        "kelas",
        "klasik",
        "kelas",
        "kopi",
        "berwarna",
        "biskuit",
        "kreatif",
        "pelayaran",
        "menari",
        "siang",
        "dinosaurus",
        "gagang pintu",
        "makan malam",
        "mimpi",
        "senja",
        "makan",
        "gajah",
        "zamrud",
        "seram",
        "elektrik",
        "selesai",
        "bunga",
        "mengikuti",
        "rubah",
        "bingkai",
        "gratis",
        "sering",
        "corong",
        "hijau",
        "gitar",
        "belanja",
        "kaca",
        "hebat",
        "cekikikan",
        "potong rambut",
        "setengah",
        "buatan rumah",
        "terjadi",
        "madu",
        "cepat",
        "seratus",
        "es",
        "igloo",
        "investasi",
        "undang",
        "ikon",
        "perkenalan",
        "candaan",
        "periang",
        "jurnal",
        "lompat",
        "bergabung",
        "kangguru",
        "keyboard",
        "dapur",
        "koala",
        "baik",
        "kaleidoskop",
        "lanskap",
        "terlambat",
        "tertawa",
        "mempelajari",
        "lemon",
        "surat",
        "lili",
        "majalah",
        "angkatan laut",
        "marshmallow",
        "labirin",
        "meditasi",
        "melodi",
        "menit",
        "monumen",
        "bulan",
        "motor",
        "gunung",
        "musik",
        "utara",
        "hidung",
        "malam",
        "nama",
        "tidak pernah",
        "negosiasi",
        "angka",
        "berlawanan",
        "gurita",
        "ek",
        "pesan",
        "buka",
        "kutub",
        "mengemas",
        "lukisan",
        "orang",
        "piknik",
        "bantal",
        "pizza",
        "podcast",
        "presentasi",
        "anak anjing",
        "puzzle",
        "resep",
        "rilis",
        "restoran",
        "berputar",
        "mengulang",
        "ruangan",
        "lari",
        "rahasia",
        "benih",
        "kapal",
        "baju",
        "sebaiknya",
        "kecil",
        "kapal antariksa",
        "menatap bintang",
        "keahlian",
        "jalan",
        "gaya",
        "matahari terbit",
        "taksi",
        "rapi",
        "timer",
        "bersama",
        "gigi",
        "turis",
        "bepergian",
        "truk",
        "bawah",
        "berguna",
        "unicorn",
        "unik",
        "mengangkat",
        "seragam",
        "vas",
        "biola",
        "pengunjung",
        "penglihatan",
        "volume",
        "melihat",
        "anjing laut",
        "berkelana",
        "dunia",
        "musim salju",
        "sehat",
        "angin puyuh",
        "x-ray",
        "gambang",
        "yoga",
        "yogurt",
        "yoyo",
        "kamu",
        "tahun",
        "enak",
        "zebra",
        "zigzag",
        "ilmu hewan",
        "zona",
        "semangat")